### ISSUE TITLE
Crash when setting font more than 2 times in a draw cycle

### ISSUE THREAD

**Issue by videah** [videah/LovePotion#1]
When setting the font to draw with `love.graphics.print()`, if it is set 3 times in a draw cycle, then a crash occurs. The cause of this is unknown, however, it could possibly be a garbage collection issue.

The following code causes a crash:

``` lua
one = love.graphics.newFont('Vera.ttf', 12)
two = love.graphics.newFont('Vera.ttf', 14)
three = love.graphics.newFont('Vera.ttf', 16)

function love.draw()

    love.graphics.setFont(one)

    love.graphics.print('Test', 0, 0)

    love.graphics.setFont(two)

    love.graphics.print('Test', 25, 25)

    love.graphics.setFont(three)

    love.graphics.print('Test', 50, 50)

end

```

But commenting out the line with `love.graphics.setFont(three)` fixes it.

Another thing to note is that LövePotion will continue to work as usual in Citra, but with a spam of memory errors in the console. It doesn't seem to fully crash in Citra.

**Comment by TurtleP** [comment]
If it's memory errors in the console, then it does sound like it's a garbage collection issue.

**Comment by VideahGams** [comment]
It should be stated, that even just creating fonts (not drawing them) can cause issues.
