### ISSUE TITLE
Font Cache

### ISSUE THREAD

**Issue by videah** [videah/LovePotion#27]
At the moment, to use different sizes of the same font you have to load it in for each size you want. With a font cache, it will just use the already loaded font to save memory.

I have implemented this, but won't be pushing it till https://github.com/xerpi/sftdlib/issues/8 is fixed.

**Comment by TurtleP** [comment]
For clarity, the rewrite uses .fnt files parsed to json with a png bitmap to render glyphs now. Any font issues should be resolved, except you'll need to make multiples of the font for other sizes.
