### ISSUE TITLE
8 bit PCM Wav Audio Distorted

### ISSUE THREAD

**Issue by andre111** [videah/LovePotion#33]
According to the errormessage printed out when trying to play unsupported audio files LövePotion supports 16 bit and 8 bit PCM wav files.

But trying to play 8 bit PCM wav files results in broken/distorted audio

**Comment by The-Sparrow** [comment]
LövePotion  on the 3DS can only support normal wav files as of now.
Try converting your wav that your having issues with to an .ogg
http://audio.online-convert.com/convert-to-ogg

**Comment by andre111** [comment]
No worries about that, they are allready 16 bit PCM.
I just thought using 8 bit PCM would work and could save half the file/memory size

**Comment by Reuh** [comment]
Actually, LövePotion should support 8bit PCM, as the audio playing code is almost the same as ctrµLua's one (which I made).
But now I realize I only tested with 16bit PCM files on ctrµLua :/
Unfortunately I don't have my 3DS now, but I'll look into this when I can.
Could you provide one file which plays distorted ? Thanks.

**Comment by VideahGams** [comment]
I haven't done much testing either (I hope you don't mind me taking some code, I was having trouble getting audio working with dsp) but I'll look into it aswell

**Comment by andre111** [comment]
Any 8bit PCM file I tested so far has distorted sound.
But here you go:
[jazz.zip](https://github.com/VideahGams/LovePotion/files/109955/jazz.zip)

**Comment by Substance12** [comment]
32bit too.
